### PR TITLE
.

### PR DESCRIPTION
**Pull request by CsirtEntelgy**

### CODE REVIEW

**Comment by AndyKnott** [comment]
I don't understand the issue - abbey.gif is now just an image of the word "Santander", no longer a screen grab from the Santander website. In what way is it a copyrighted image?

**Comment by CsirtEntelgy** [comment]
.

**Comment by AndyKnott** [comment]
Thanks for your reply. I have looked at the link and I'm definitely not using their logo, and the text I am using isn't the same font or colour. Is the website saying that they have trademarked the word "Santander"? If so, I guess I can change it to read "Spanish bank" with no further problems?

**Comment by CsirtEntelgy** [comment]
.

**Comment by AndyKnott** [comment]
OK, hopefully this will be OK:

image

Thanks,

Andy

**Comment by CsirtEntelgy** [comment]
.

**Pull request closed without merging**
